# Generated by Django 3.1.6 on 2021-07-03 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnsCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('snsmessagemodel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.snsmessagemodel')),
            ],
        ),
    ]
